source 'https://github.com/CocoaPods/Specs.git'

target 'URBNEnvironmentPicker', :exclusive => true do
  pod "URBNEnvironmentPicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "URBNEnvironmentPicker", :path => "../"

  
end
