# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2
language: objective-c
before_install: cd Example && rm -rf Pods && pod install && cd -
script:
- xcodebuild -workspace Example/URBNEnvironmentPicker.xcworkspace -scheme Example clean build -destination "platform=iOS Simulator,name=iPhone 6,OS=latest" -destination-timeout 120 test
